export const tutoriasData = [
	{
		id: 1,
		name: 'HTML y CSS',
		time1: 'Lunes 18:30 hs',
		teacher: 'Diana Mottura',
		zoom: 'https://meet.google.com/xrs-ycfy-ero',
		icon: 'FaHtml5',
	},
	{
		id: 2,
		name: 'JavaScript',
		time1: 'Martes 18:00 hs',
		time2: 'Jueves 10:00 hs',
		teacher: 'Guillermo Bravo',
		zoom: 'https://meet.google.com/yii-ksiu-wmo',
		icon: 'FaJsSquare',
	},
	{
		id: 3,
		name: 'React',
		time1: 'Martes 10:00 hs',
		time2: 'Jueves 21:00 hs',
		teacher: 'Jorge Ignacio Garay',
		zoom: 'https://meet.google.com/ood-rhnc-pjw',
		icon: 'FaReact',
	},
	{
		id: 4,
		name: 'Backend',
		time1: 'Lunes 12:30 hs',
		time2: 'Viernes 18:30 hs',
		teacher: 'Marcos Gual',
		zoom: 'https://meet.google.com/zmp-pjse-dum',
		icon: 'FaNode',
	},
];
