export const tutoriasData = [
	{
		id: 1,
		name: 'HTML y CSS',
		time1: 'Lunes 18:30 hs',
		time2: 'Miércoles 9:30 hs',
		teacher: 'Diana Mottura',
		zoom: 'example.zoom',
		icon: 'FaHtml5',
	},
	{
		id: 2,
		name: 'JavaScript',
		time1: 'Martes 19:00 hs',
		time2: 'Sábados 12:00 hs',
		teacher: 'Matias Domínguez',
		zoom: 'example.zoom',
		icon: 'FaJsSquare',
	},
	{
		id: 3,
		name: 'React',
		time1: 'Lunes 12:30 hs',
		time2: 'Viernes 18:30 hs',
		teacher: 'Marcos Gual',
		zoom: 'example.zoom',
		icon: 'FaReact',
	},
	{
		id: 4,
		name: 'Backend',
		time1: 'Lunes 12:30 hs',
		time2: 'Viernes 18:30 hs',
		teacher: 'Marcos Gual',
		zoom: 'example.zoom',
		icon: 'FaNode',
	},
];
